"""HTML formatter for SupportAnswerResult — converts structured Claude output
to an HTML string suitable for Odoo HTML fields.

Kept separate from support_answerer.py so the Claude orchestration and the
presentation layer can change independently.
"""

from __future__ import annotations

from reva.types import SupportAnswerResult

_STATUS_BADGE: dict[str, str] = {
    "answered": (
        '<span style="font-size:0.75em;font-weight:bold;color:#1a7f37;'
        'background:#dafbe1;border:1px solid #82cfae;border-radius:3px;'
        'padding:1px 5px;margin-right:6px;vertical-align:middle;">answered</span>'
    ),
    "partially_answered": (
        '<span style="font-size:0.75em;font-weight:bold;color:#9a6700;'
        'background:#fff8c5;border:1px solid #e3b341;border-radius:3px;'
        'padding:1px 5px;margin-right:6px;vertical-align:middle;">partially answered</span>'
    ),
    "cannot_answer": (
        '<span style="font-size:0.75em;font-weight:bold;color:#cf222e;'
        'background:#fff0ee;border:1px solid #ff8182;border-radius:3px;'
        'padding:1px 5px;margin-right:6px;vertical-align:middle;">cannot answer</span>'
    ),
}

_REQUEST_KIND_LABEL: dict[str, str] = {
    "question": "question",
    "change_request": "change request",
    "bug_report": "bug report",
    "mixed": "question + change request",
    "other": "other",
}

_SOURCE_KIND_LABEL: dict[str, str] = {
    "core_doc": "core doc",
    "repo_doc": "repo doc",
    "repo_code": "repo code",
}


def format_support_html(result: SupportAnswerResult) -> str:
    """Convert a SupportAnswerResult into an HTML string suitable for Odoo HTML fields."""
    parts: list[str] = []

    # Status + request-kind banner
    parts.append(
        '<p style="font-size:0.85em;font-weight:bold;color:#24292f;'
        'border-bottom:1px solid #d0d7de;padding-bottom:6px;margin-bottom:4px;">'
        + _STATUS_BADGE.get(result.answer_status, "")
        + _esc(_REQUEST_KIND_LABEL.get(result.request_kind, result.request_kind))
        + "</p>"
    )

    # Handoff hint — point the consultant at the next action when this
    # request also looks like a change request / bug report.
    handoff = result.handoff
    if handoff.suggest_analysis or handoff.suggest_issues:
        actions = []
        if handoff.suggest_analysis:
            actions.append("Analyse Ticket")
        if handoff.suggest_issues:
            actions.append("Create Issues")
        hint = f"<strong>Next step:</strong> consider {' / '.join(actions)}."
        if handoff.rationale:
            hint += f" {_esc(handoff.rationale)}"
        parts.append(f'<p style="font-size:0.85em;color:#57606a;">{hint}</p>')

    if result.answer_status == "cannot_answer":
        # Product rule: no drafted prose to fact-check — only the reason and
        # what's missing, so the consultant sees the gap instead of a
        # paragraph they must verify.
        parts.append("<h2>Cannot Answer</h2>")
        parts.append(f"<p>{_esc(result.cannot_answer_reason or '')}</p>")
        if result.open_questions:
            items = "".join(f"<li>{_esc(q)}</li>" for q in result.open_questions)
            parts.append(f"<h2>Open Questions</h2><ul>{items}</ul>")
        parts.append("<p><em>Generated by REVA</em></p>")
        return "\n".join(parts)

    parts.append("<h2>Answer</h2>")
    parts.append(_paragraphs(result.answer))

    if result.answer_status == "partially_answered" and result.open_questions:
        items = "".join(f"<li>{_esc(q)}</li>" for q in result.open_questions)
        parts.append(f"<h2>Open Questions</h2><ul>{items}</ul>")

    if result.sources:
        items = []
        for source in result.sources:
            bits = [f"<strong>{_esc(source.title or source.ref)}</strong>"]
            if source.title and source.ref:
                bits.append(f"<small>({_esc(source.ref)})</small>")
            bits.append(f"<small>{_esc(_SOURCE_KIND_LABEL.get(source.kind, source.kind))}</small>")
            items.append("<li>" + " ".join(bits) + "</li>")
        parts.append(f"<h2>Sources</h2><ul>{''.join(items)}</ul>")

    parts.append("<p><em>Generated by REVA</em></p>")
    return "\n".join(parts)


def _paragraphs(text: str) -> str:
    """Render the model's draft as escaped paragraphs, split on blank lines.

    The answer is always ESCAPED, never injected as markup: it is model output
    shaped by untrusted customer text, and this HTML lands in a consultant's
    Odoo view, so a prompt-injected `<script>` or `onerror=` would execute
    there. The skill therefore asks for plain text with blank-line paragraph
    breaks, and this restores the structure safely — escaping alone would
    collapse a multi-paragraph draft into one unreadable run.
    """
    blocks = [block.strip() for block in text.split("\n\n") if block.strip()]
    if not blocks:
        return ""
    return "".join(f"<p>{_esc(block)}</p>" for block in blocks)


def _esc(text: str) -> str:
    """Minimal HTML escaping for user-supplied strings."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
